
# -------------------------------------------------------
# Utilities commands
#--------------------------------------------------------

# Scripts
bootstrap:
	./scripts/bootstrap.sh

# Docker utility commands
kill:
	@docker kill $$(docker ps -q)

rmc:
	@docker rm $$(docker ps -a -q)

rmi:
	@docker rmi $$(docker images -q)
	
#--------------------------------------------------------
# Postgresql database commands
#--------------------------------------------------------
# You need to install postgresql-client first
connect-db:
	psql -h localhost -p 5432 -d budgetapp_dev -U budget

# Useful commands
# \l  - List available databases
# \dt - List available tables
# \du - List users and their roles
# \q - Quit psql

remove-db-tabels:
	psql -h localhost -p 5432 -d budgetapp_dev -U budget -f scripts/clean_db.sql
	
#--------------------------------------------------------
# Django migrations commands
#--------------------------------------------------------
clear-migration-history:
	python manage.py migrate --fake budgets zero
	python manage.py migrate --fake users zero
	python manage.py showmigrations

remove-migration-files:
	find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
	find . -path "*/migrations/*.pyc" -delete

makemigrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate


